import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from './_component/navbar/navbar'
import Sidebar from './_component/sidebar/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <Navbar />
        <div className='flex h-full pt-20 w-full'>
          <Sidebar/>
          <section className='flex w-full'>
            {children}
          </section>
        </div>
    </>
  )
}
